import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import { ParcelLab } from '@parcellab/js-plugin/bundle/module.min'
import '@parcellab/js-plugin/bundle/module.min.css'
import { useEffect, useRef } from 'react'

export default function Home() {
  const divRef = useRef()
  useEffect(() => {
    const loadPlPlugin = async () => {
      const plModule = (await import('@parcellab/js-plugin/bundle/module.min'))
      const ParcelLab = plModule.ParcelLab
      
      const options = { rerouteButton: 'left', show_searchForm: 'true', userId: '1613928' };
      const plPlugin = new ParcelLab('#pl-trace', options);
      plPlugin.initialize()
    }

    if (divRef.current) {
      console.log(divRef.current)
      loadPlPlugin()
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div id="pl-trace" ref={divRef}>
          yolo
        </div>
    </main>
    </div>
  )
}
